OCHA-DAP/pa-anticipatory-action

README.md

Updating the readme. 
Not sure if the repo structure is an overkill

update general readme

---

analyses/malawi/notebooks/gee_example.ipynb
indicators/drought/gee_example.ipynb
requirements.txt

Adding in the sample GEE notebook for potential future work. This could be removed if not used in the end.

Gee testing

---

analyses/ethiopia/notebooks/script/eth_rainfall_aggregate.py

Adding simple file for Amadou to work on the dashboard. Merging without review for now

Eth dashb mockup

---

dashboard/rsconnect/shinyapps.io/humdata/dashboard.dcf
dashboard/server.R
dashboard/ui.R

Updated the ICPAC image, added a note about FN having fresher data, and updated the "last update" date. Should be straightforward to merge.

icpac update + note that fn published new data

---

requirements.txt
src/indicators/flooding/glofas/glofas.py
tests/test_glofas.py

I've been spoiled with Pandas and didn't realize that `xarray` was not automatically closing files. To fix this:
- converted `open_dataset` to `load_dataset`
- wrapped `open_mfdataset` in a with-as statement
@hannahker perhaps this will solve your Google Drive issue?

Fixed bug where GloFAS files are not closed

---

analyses/npl/06_return_periods.md
src/indicators/flooding/glofas/utils.py

When I discovered that the Nepal RPs that I calculated were not matching those in the GloFAS web interface, I thought that perhaps the difference came about because I was not doing it analytically. 
This notebook explores the difference when doing the analytical calculation (fitting a GEV) compared to the empirical method. The agreement is best for the lower RP values, but using the GEV doesn't seem to solve the mismatch with GloFAS.
I also updated the utils to be able to use the analytical method.

Return period calculations

---

analyses/npl/07_water_level.md

Short notebook for examining and cleaning the water level data, and creating a summary csv file for the stations of interest

Nepal water level data

---

.gitignore

ignore ipynb

---

analyses/malawi/notebooks/mwi_monthlytotal_corr_dryspells_adm1.md

Make the months of interest a variable instead of hard-coded
Very small PR, so not reviewing

make months included variable

---

src/indicators/flooding/glofas/utils.py

I messed up a merge and left the HEAD line in one of the GloFAS files, this PR is to remove it

Fix bad merge

---

analyses/npl/02_glofas_skill.md
analyses/npl/05.5_station_correlation_viz.md
analyses/npl/06_return_periods.md
requirements.txt
src/indicators/flooding/glofas/utils.py
src/nepal/config.yml
src/nepal/get_glofas_data.py

Update station coordinates to GloFAS model v3

Nepal update station coords

---

analyses/npl/02_glofas_skill.md
src/indicators/flooding/glofas/utils.py
src/utils_general/statistics.py

moving the function to `utils_general` and taking out the mean calculation such that it can be used more generally.

generalize mpe

---

analyses/malawi/dryspells_trigger/01_chirps_dry_spell_detection.R

@Tinkaa 
Minimal clean-up changes:
- shortened name of the binary indicating if the dry spell was confirmed after the rainy season onset or before its cessation;
- kept the binary variable in the dataset that saves.
I do not see on HDX a reference to another variable that would be a approximation of whether or not the DS was during the rainy season.
The dataset generated by this code replicates what is on HDX and adds the binary `during_rainy_season` variable.
I saved the updated csv on the Data GDrive folder. If you merge this while I'm away, please make sure to upload the new version to HDX along with the updated methodology.

Mwi full ds list revised

---

analyses/npl/02_glofas_skill.md
src/indicators/drought/ecmwf_seasonal/processing.py
src/indicators/flooding/glofas/utils.py
src/utils_general/statistics.py

proposal to generalize the CRPS
- largest change is to do the normalization after selecting on a threshold. lets discuss if that makes sense. 
- I tried to generalize the functions more, but since glofas uses >thresh and ecmwf <=thresh I couldn't really make it work. Let me know if you think there is a better way to generalize. 
- For ecmwf it is really slow. I think it is mainly the `xs.crps_ensemble` so we can probably not change much about that, but let me know if you think we can.

refactor crps

---

analyses/npl/08_water_level_events.md

A small change I made awhile ago and forgot to open a PR for!

Create count of false positives with warning readiness trigger

---

analyses/npl/11_forecast_rp.md
src/indicators/flooding/glofas/utils.py
src/utils_general/statistics.py

Script to calculate the equivalent return period in the forecasts

Nepal forecast return period

---

analyses/malawi/README.md

Adding in some basic content for the flooding work :) 
- Do you think that this is the right level of detail?
- What do you think of the status badge?

Update mwi readme with flooding overview

---

analyses/country_template/README.md

Add status badges to readme template

---

analyses/malawi/flooding_trigger/08_mwi_event_visualization.md

Just adding an exploratory notebook to visualize GloFAS values around the time of a flood onset.

Add notebook to visualize glofas around flood onset

---

analyses/malawi/README.md

Update mwi readme
do you think it is detailed enough? 
Also, I would like to update the folder name to `mwi` instead of `malawi`, but we have shared the links to the summary documents (gh pages) with external partners. Would you know a solution to this?

update readme mwi

---

analyses/bfa/README.md
analyses/bgd/README.md
analyses/malawi/README.md

Pretty self-explanatory and minor :

Normalize headers

---

analyses/bgd/README.md

Since we're cleaning up the READMEs, updated the Bangladesh one to better reflect the present situation

Update Bangladesh README

---

analyses/npl/README.md

Nepal README

---

analyses/mwi/dryspells_trigger/12_arc2_identify_dry_spells.md

@caldwellst @hannahker super small change to update an old path for saving. So just for your awareness. @caldwellst feel free to merge directly.

fix saving path

---

src/eth/eth_foodinsec_trigger.py
src/indicators/food_insecurity/config.py
src/indicators/food_insecurity/ipc_definemetrics.py
src/indicators/food_insecurity/process_fewsnet_subnatpop.py
src/indicators/food_insecurity/process_fewsnet_worldpop.py
src/indicators/food_insecurity/process_globalipc.py
src/indicators/food_insecurity/utils.py
src/som/som_foodinsec_trigger.py

Changes the usage of country name to iso3 as we have renamed all the folders to the iso3 codes. 
Also does some small other changes such as rounding numbers and adding the projection period. 
Note that the scripts are very messy and need a bigger round of refactoring still!

Food insecurity: small refactor

---

src/indicators/drought/ecmwf_seasonal/ecmwf_seasonal.py

Small PR to 
- Enable input of `year_min` and `year_max` to `download()`. Before the years could only be changed in the `ecmwf_seasonal.py` script, but now any year_min and year_max can be given when download is called
- Enable a custom list of months to be downloaded. Before the whole year had to be downloaded. 
- Remove the argument `split_by_month` as we haven't used it and could cause confusion when using the custom list of month
This PR merges into the branch of PR #190 so better to review and merge that branch first.

change year and month input

---

analyses/mdg/mdg_plague_exploration.md

Save figures and some small improvements

minor improvements

---

analyses/mdg/mdg_plague_exploration.md

New data was received and Leonardo asked me to update the analysis, so I updated the code + slides. No actual change, essentially, the only difference was a couple additional cases at existing peaks in 2017 (they fixed some of the issues with ADM2 codes in the data) and new data (no new cases) until yesterday.

Update MDG analysis with new data to November 8 2021

---

analyses/mwi/dryspells_trigger/09_ecmwf_monthly_skill_dryspells.md

Small PR to add a histogram, and update the leadtime from 2&4 to 3 months as this is what is used for the trigger now.

improve histogram

---

src/mwi/compute_trigger_ecmwf.py

- run all variations of methods for the dates we are interested in. Previously I was changing the parameters and running the script, but now it is more transparent which different variations were tested
- make `use_unrounded_area_coords` a private constant instead of global as we are adjusting its value
Could you have a double-check if the logic of running with the different parameters makes sense?

run all methods

---

analyses/mwi/dryspells_trigger/exploration/aggr_ecmwf_compare_methods.md

Notebook to compare for pred trigger if for different methods of aggregation the median changes. 
@caldwellst would you be willing to think along from a more conceptual perspective and see if the plots make sense or that you would visualize it in another way?

plots to compare methods

---

analyses/tcd/notebooks/forecasts/tcd_seas_bavg_precip_observed.md
src/tcd/get_chirps_data.py

Notebook that processes and analysis historical precipitation, with especially a focus on the occurence of below average precipitation. 
Also compares to a list of historical drought years. 
Serves as a basis to compare precipitation forecasts to.

TCD hist precip analysis

---

src/mwi/compute_trigger_ecmwf.py

Small pr to also add the `source_cds` parameter to the trigger script. 
`source_cds=False` is currently not yet implemented in the trigger script but at least everything works now for the `source_cds=True` and `source_cds=False` will be easier to add

add source cds

---

analyses/tcd/notebooks/forecasts/tcd_tercile_check.md

Making a PR for the analysis used to address #245

Tercile check notebook

---

src/indicators/drought/ecmwf_seasonal/processing.py

Update the filename of the seasonal forecast data directly retrieved from ecmwf
This is hardcoded atm with the idea that it was not worth making nice code for if we gonna change the structure for toolbox anyway

update ecmwf filename

---

analyses/mwi/dryspells_trigger/15_mwi_obs_trigger_monitoring.md
analyses/mwi/dryspells_trigger/exploration/test_arc2_processing.md
src/indicators/drought/arc2_precipitation.py

Quick update to analysis code to address #262. Remembered why I wasn't using `rioxarray.open_rasterio()` was because it was causing the `"Unknown dims"` error because by default the data is stored with a 4th dimension `band`. I've moved back to using `xarray` to load in the data and problems are gone. I've also fixed the `_fillValue` error and should be able to load in non-contiguous dates. Hopefully your testing shows the same!

Update ARC2 code for trigger monitoring

---

analyses/uga/docs/uga_flood_risk.Rmd

Fixed the label of the column to say 20% not 80%

fixed typo in colname

---

analyses/tcd/notebooks/forecasts/tcd_rainy_onset.md

Exploration of the onset dates in TCD. 
Not critical for anything right now, but couldn't get rid of my curiosity to see if it shows different patterns than seasonal below average precipitation (which it does!)

analysis rainy onset in tcd

---

src/indicators/drought/chirps_rainfallobservations.py
src/mwi/chirps_malawi.py

Adjust very ugly code to at least get the downloading working. 
This code is soon to be replaced with toolbox code, so not putting effort here to make it nice.

Bug chirps download

---

analyses/mdg/mdg_plague_trigger_monitoring.md

Just a very quick change to ensure that the monitoring worked without a hitch. As well, just put the latest date automatically to today so we don't have to adjust anything in the script, just save data and run.

Slight fix to MDG monitoring script to remove datetime errors

---

analyses/mdg/mdg_plague_trigger_monitoring.md

Very small changes to enable file saving and check that filepath is correct.

add file saving

---

analyses/ssd/flood_trigger/ssd_floodscan_roi.md

Very small PR, but always like to have it documented where files are saved, so added that

save roi stats file

---

analyses/mdg/mdg_plague_exploration.md
analyses/mdg/mdg_plague_trigger_monitoring.md

dont need to really review, just quick graph so I could use it for a presentation

quick cases graph

---

analyses/ssd/flood_trigger/ssd_blog_graph.R

Simple update to blog graph for ODSG presentation.

Update SSD blog graph

---

analyses/mdg/mdg_plague_trigger_monitoring.md

rem suspected cases

---

analyses/bfa/drought_trigger/02_bfa_seas_bavg_precip_observed.md
analyses/bfa/drought_trigger/03_bfa_seas_bavg_precip_corr_obsfor.md
analyses/bfa/drought_trigger/04_bfa_seas_bavg_iriforecast.md
analyses/bfa/drought_trigger/05_bfa_seas_bavg_iriforecast_peradm1.md
analyses/bfa/drought_trigger/06_bfa_iri_rpsskill.md
analyses/bfa/drought_trigger/exploration/bfa_ecmwf_seasonal_tercile.md
pyproject.toml

add jupyter-black and fix few small things to make code run again

clean and add notes

---

src/indicators/flooding/glofas/get_stations.py

Quick script to get GloFAS station for toolbox config. No rush for review.

Get GlofAS stations
